[custom]

[[custom_groups]]
import = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/groups.txt"

[[rulesets]]
import = "https://raw.githubusercontent.com/CuminLo/clash-rules/master/rulesets.toml"

enable_rule_generator=true

overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/CuminLo/clash-rules/main/GeneralClashConfig_lohome_meta.yaml

;luck