
#---------------------------------------------------#
# 配置文件需要放置在 $HOME/.config/clash/config.yml
# 或者运行目录下的config.yml
# fallback: 与 nameserver 并发发起DNS请求，如果解析的IP地址是CN就用 nameserver，如果不是 CN 就用 fallback
# fake-ip-filter: 代表匹配的不走fake-ip
#---------------------------------------------------#
# 混合端口 HTTP和SOCKS5用一个端口
port: 7890
socks-port: 7891
mixed-port: 7893
allow-lan: true
bind-address: '*'
skip-auth-prefixes:
  - 127.0.0.1/8
  - ::1/128
ipv6: false
find-process-mode: strict
log-level: debug
mode: rule
external-controller: 0.0.0.0:9090
external-ui: yacd
external-ui-url: "https://mirror.ghproxy.com/https://github.com/haishanh/yacd/archive/gh-pages.zipp"
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
geodata-loader: standard
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
keep-alive-interval: 15
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
tun:
  enable: true
  stack: gvisor # system gvisor mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-redirect: true
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  route-exclude-address-set: [cncidr]
  route-exclude-address:
    - 74.48.160.148/32
    - 122.224.0.0/12
    - 119.96.0.0/13
    - 106.56.0.0/13
    - 120.133.71.0/24
    - 163.181.166.0/24
    - 163.181.164.0/24
    - 163.181.201.0/24
    - 163.181.199.0/24
    - 163.181.42.0/24
    - 163.181.39.0/24
    - 47.89.66.0/24
    - 128.1.157.0/24
    - 163.181.23.0/24
    - 163.181.129.0/24
    - 163.181.81.0/24
    - 163.181.82.0/24
    - 163.181.128.0/24
    - 163.181.160.0/24
    - 14.112.0.0/12
    - 183.0.0.0/10
    - 223.5.5.5/32
    - 223.6.6.6/32
    - 119.29.29.29/32
    - 114.114.114.114/32
    - 1.12.12.12/32
    - 180.76.76.76/32
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - ::/127
    - fc00::/7
    - fe80::/10
    - ff00::/8
profile:
  store-selected: true
  store-fake-ip: false
dns:
  enable: true
  use-system-hosts: true
  ipv6: false
  prefer-h3: true
  respect-rules: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip # fake-ip or redir-host
  fake-ip-range: 28.0.0.1/8
  use-hosts: true
  default-nameserver: [223.5.5.5, 119.29.29.29, 114.114.114.114]
  nameserver-policy:
    "+.lohome.top,+.syncthing.net,+.zerotier.net":
      - https://223.5.5.5/dns-query#h3=true
      - https://1.12.12.12/dns-query
    "rule-set:direct,mydirect,china,chinax,chinatest": 
      - https://223.5.5.5/dns-query#h3=true
      - https://1.12.12.12/dns-query
    "geosite:tracker,private":
      - https://223.5.5.5/dns-query#h3=true
      - https://1.12.12.12/dns-query
    "geosite:cn,tld-cn,category-games@cn,apple-cn,apple,microsoft@cn,onedrive": 
      - https://223.5.5.5/dns-query#h3=true
      - https://1.12.12.12/dns-query
    "rule-set:github,google,gfw,proxy,tiktok,openai,proxyclassical,global":
      - https://dns.google/dns-query#ecs=120.76.0.0/14&ecs-override=true
      - https://dns12.quad9.net/dns-query#ecs=120.76.0.0/14&ecs-override=true
    "geosite:github,google,facebook,twitter,tiktok,openai":
      - https://dns.google/dns-query#ecs=120.76.0.0/14&ecs-override=true
      - https://dns12.quad9.net/dns-query#ecs=120.76.0.0/14&ecs-override=true
  proxy-server-nameserver: 
      - https://223.5.5.5/dns-query#h3=true
  nameserver: 
    - https://223.5.5.5/dns-query#h3=true
    - https://1.12.12.12/dns-query
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "+.*"

sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.apple.com"

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  mydirect:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/CuminLo/clash-rules/master/DirectDomain.list"
    path: ./ruleset/mydirect.yaml
    interval: 1000

  myproxy:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/CuminLo/clash-rules/master/Proxy.list"
    path: ./ruleset/myproxy.yaml
    interval: 1200

  binance:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Binance/Binance_No_Resolve.yaml"
    path: ./ruleset/binance.yaml
    interval: 86400

  crypto:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Crypto/Crypto_No_Resolve.yaml"
    path: ./ruleset/crypto.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  appleall:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple_Classical_No_Resolve.yaml"
    path: ./ruleset/appleall.yaml
    interval: 86400

  netflix:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix_Classical_No_Resolve.yaml"
    path: ./ruleset/netflix.yaml
    interval: 86400

  youtube:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube_No_Resolve.yaml"
    path: ./ruleset/youtube.yaml
    interval: 86400

  googleFCM:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleFCM/GoogleFCM_No_Resolve.yaml"
    path: ./ruleset/googleFCM.yaml
    interval: 86400

  google:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google_No_Resolve.yaml"
    path: ./ruleset/google.yaml
    interval: 86400

  openai:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml"
    path: ./ruleset/openai.yaml
    interval: 86400

  bahamut:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bahamut/Bahamut_No_Resolve.yaml"
    path: ./ruleset/bahamut.yaml
    interval: 86400

  amazon:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Amazon/Amazon_No_Resolve.yaml"
    path: ./ruleset/amazon.yaml
    interval: 86400

  onedrive:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OneDrive/OneDrive_No_Resolve.yaml"
    path: ./ruleset/onedrive.yaml
    interval: 86400

  microsoft:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft_No_Resolve.yaml"
    path: ./ruleset/microsoft.yaml
    interval: 86400

  discord:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Discord/Discord_No_Resolve.yaml"
    path: ./ruleset/discord.yaml
    interval: 86400

  twitter:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter_No_Resolve.yaml"
    path: ./ruleset/twitter.yaml
    interval: 86400

  tiktok:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok_No_Resolve.yaml"
    path: ./ruleset/tiktok.yaml
    interval: 86400

  github:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub_No_Resolve.yaml"
    path: ./ruleset/github.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  china:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_No_Resolve.yaml"
    path: ./ruleset/china.yaml
    interval: 86400

  chinax:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical_No_Resolve.yaml"
    path: ./ruleset/chinax.yaml
    interval: 86400

  chinatest:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaTest/ChinaTest_Classical_No_Resolve.yaml"
    path: ./ruleset/chinatest.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  global:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Global/Global_Classical_No_Resolve.yaml"
    path: ./ruleset/global.yaml
    interval: 86400

  proxyclassical:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Proxy/Proxy_Classical_No_Resolve.yaml"
    path: ./ruleset/proxyclassical.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  chinaips:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaIPs/ChinaIPs_IP.yaml"
    path: ./ruleset/chinaips.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400