
#---------------------------------------------------#
# 配置文件需要放置在 $HOME/.config/clash/config.yml
# 或者运行目录下的config.yml
# fallback: 与 nameserver 并发发起DNS请求，如果解析的IP地址是CN就用 nameserver，如果不是 CN 就用 fallback
# fake-ip-filter: 代表匹配的不走fake-ip
#---------------------------------------------------#
# 混合端口 HTTP和SOCKS5用一个端口
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
allow-lan: true
bind-address: '*'
skip-auth-prefixes:
  - 127.0.0.1/8
  - ::1/128
ipv6: false
find-process-mode: strict
log-level: debug
mode: rule
external-controller: 127.0.0.1:9090
external-ui: Yacd-meta
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
keep-alive-interval: 15
geox-url:
  geoip: "https://ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
tun:
  enable: true
  stack: mixed # system gvisor mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-redir: true
  auto-redirect: false
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  device: utunMeta
  route-exclude-address-set:
    - cncidr
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  use-system-hosts: true
  ipv6: false
  prefer-h3: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host # fake-ip or redir-host
  # fake-ip-range: 28.0.0.1/8
  use-hosts: true
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "geosite:google":
      - tls://8.8.4.4
      - tls://8.8.8.8
    "geosite:geolocation-!cn":
      - tls://8.8.4.4
      - https://1.0.0.1/dns-query
    "geosite:category-ads-all": rcode://success
  proxy-server-nameserver:
    - https://doh.apad.pro/dns-query
    - https://dns.alidns.com/dns-query
  nameserver:
    - https://doh.apad.pro/dns-query
    - https://doh.pub/dns-query

ntp:
  enable: true
  write-to-system: false
  server: ntp.tencent.com
  port: 123
  interval: 30

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false

rule-providers:
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  customcidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/CuminLo/clash-rules/master/CustomCidr.txt
    path: ./ruleset/customcidr.yaml
    interval: 86400