
#---------------------------------------------------#
# 配置文件需要放置在 $HOME/.config/clash/config.yml
# 或者运行目录下的config.yml
# fallback: 与 nameserver 并发发起DNS请求，如果解析的IP地址是CN就用 nameserver，如果不是 CN 就用 fallback
# fake-ip-filter: 代表匹配的不走fake-ip
#---------------------------------------------------#
# 混合端口 HTTP和SOCKS5用一个端口
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: false
bind-address: '*'
skip-auth-prefixes:
  - 127.0.0.1/8
  - ::1/128
secret: xxooooxx
authentication:
  - "admin:xxooooxx"
ipv6: true
find-process-mode: strict
log-level: debug
mode: rule
external-controller: 0.0.0.0:9090
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
keep-alive-interval: 60
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
tun:
  enable: true
  stack: mixed # system gvisor mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-redirect: true
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  route-exclude-address-set: [lancidr, cncidr]
  route-exclude-address: [223.5.5.5/32, 119.29.29.29/32, 114.114.114.114/32, 1.12.12.12/32, 74.48.160.148/32]
  exclude-package: [
    "cmb.pb",
    "cn.gov.pbc.dcep",
    "com.MobileTicket",
    "com.adguard.android",
    "com.ainemo.dragoon",
    "com.alibaba.android.rimet",
    "com.alicloud.databox",
    "com.amazing.cloudisk.tv",
    "com.autonavi.minimap",
    "com.bilibili.app.in",
    "com.bishua666.luxxx1",
    "com.cainiao.wireless",
    "com.chebada",
    "com.chinamworld.main",
    "com.cmbchina.ccd.pluto.cmbActivity",
    "com.coolapk.market",
    "com.ctrip.ct",
    "com.dianping.v1",
    "com.douban.frodo",
    "com.eg.android.AlipayGphone",
    "com.farplace.qingzhuo",
    "com.hanweb.android.zhejiang.activity",
    "com.leoao.fitness",
    "com.lucinhu.bili_you",
    "com.mikrotik.android.tikapp",
    "com.moji.mjweather",
    "com.motorola.cn.calendar",
    "com.motorola.cn.lrhealth",
    "com.netease.cloudmusic",
    "com.sankuai.meituan",
    "com.sina.weibo",
    "com.smartisan.notes",
    "com.sohu.inputmethod.sogou.moto",
    "com.sonelli.juicessh",
    "com.ss.android.article.news",
    "com.ss.android.lark",
    "com.ss.android.ugc.aweme",
    "com.tailscale.ipn",
    "com.taobao.idlefish",
    "com.taobao.taobao",
    "com.tencent.mm",
    "com.tencent.mp",
    "com.tencent.soter.soterserver",
    "com.tencent.wemeet.app",
    "com.tencent.weread",
    "com.tencent.wework",
    "com.ttxapps.wifiadb",
    "com.unionpay",
    "com.unnoo.quan",
    "com.wireguard.android",
    "com.xingin.xhs",
    "com.xunmeng.pinduoduo",
    "com.zui.zhealthy",
    "ctrip.android.view",
    "io.kubenav.kubenav",
    "org.geekbang.geekTime",
    "tv.danmaku.bili"
  ]
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  use-system-hosts: true
  ipv6: true
  prefer-h3: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip # fake-ip or redir-host
  fake-ip-range: 28.0.0.1/8
  use-hosts: true
  default-nameserver: [223.5.5.5, 119.29.29.29, 114.114.114.114]
  nameserver-policy:
    "+.lohome.top, +.syncthing.net": [https://223.5.5.5/dns-query, https://1.12.12.12/dns-query]
    "geosite:tracker,private": [223.5.5.5, 119.29.29.29]
    "geosite:cn,china-lis,category-games@cn,apple,microsoft@cn,onedrive": [https://223.5.5.5/dns-query, https://1.12.12.12/dns-query]
    "geosite:google,geolocation-!cn": [https://8.8.4.4/dns-query, https://9.9.9.11/dns-query]
    "geosite:category-ads-all": rcode://success
  proxy-server-nameserver: [https://8.8.4.4/dns-query, https://9.9.9.11/dns-query]
  nameserver: [https://8.8.4.4/dns-query, https://9.9.9.11/dns-query]
  fake-ip-filter:
    - "WORKGROUP"
    - "+.apple.com"
    - "+.synology.me"
    - "+.synology.com"
    - "+.lohome.top"
    - "+.ddnsfree.com"
    - "+.newlink.com"
    - "+.newlinks.com"
    - "+.shylwlkj.com"
    - "+.nlsaas.com"
    - "+.nlktj.cn"
    - "+.lingnengsaas.com"
    - "+.unicornenergy.cn"
    - "+.czb365.com"
    - "+.tencentcdb.com"
    - "+.dnsapi.cn"
    - "+.10010.com"
    - "+.lan"
    - "+.oray.net"
    - "+.localdomain"
    - "+.example"
    - "+.invalid"
    - "+.localhost"
    - "+.test"
    - "+.local"
    - "+.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "+.router.asus.com"
    - "+.google.com"
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - shark007.net
    - ntp.ntsc.ac.cn
    - '*.mcdn.bilivideo.cn'
    - "+.media.dssott.com"
    - ntp.ntsc.ac.cn
    - '*.mcdn.bilivideo.cn'
    - +.media.dssott.com
    - +.cmbchina.com
    - +.cmbimg.com
    - local.adguard.org
    - +.sandai.net
    - +.n0808.com

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.apple.com"

rule-providers:
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400